[package]
name = "authentication"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
models = { path = "../models" }
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "9"
chrono = { version = "0.4", features = ["serde"] }
axum = { version = "0.8.6", features = ["macros"] }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "macros", "chrono"] }
bcrypt = "0.15"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
lettre = { version = "0.11", features = ["tokio1-native-tls"] }
tokio = { workspace = true }
