[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
models = { path = "../lib/models" }
services = { path = "../lib/services" }
authentication = { path = "../lib/authentication" }
utils = { path = "../lib/utils" }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "macros", "chrono"] }
axum = { version = "0.6", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "9"
actix-web = "4"